#!/usr/bin/env bash
#
set -eo pipefail

export GH_PAGER="cat"

#shellcheck disable=SC2155
readonly BASEDIR=$(dirname "$(realpath "$0")")
#shellcheck disable=SC2034
readonly POLL_INTERVAL_SECS=${GH_POLL_INTERVAL_SECS:-30}
#shellcheck disable=SC2034
GH_MERGE_TRAIN_REBASE="true"
#shellcheck disable=SC2034
readonly GH_MERGE_TRAIN_MAX_ATTEMPTS=${GH_MERGE_TRAIN_MAX_ATTEMPTS:-4}
#shellcheck disable=SC2034
readonly GH_MERGE_TRAIN_BOT_LABEL=${GH_MERGE_TRAIN_BOT_LABEL:-}
#shellcheck disable=SC2034
readonly GH_MERGE_TRAIN_DEPENDABOT_REBASE=${GH_MERGE_TRAIN_DEPENDABOT_REBASE:-}
#shellcheck disable=SC2034
readonly GH_MERGE_TRAIN_DEPENDABOT_RECREATE=${GH_MERGE_TRAIN_DEPENDABOT_RECREATE:-}
#shellcheck disable=SC2034
readonly GH_MERGE_TRAIN_RETRY_FAILED_JOBS=${GH_MERGE_TRAIN_RETRY_FAILED_JOBS:-false}
#shellcheck disable=SC2034
readonly GH_MERGE_TRAIN_CURRENT_BRANCH=${GH_MERGE_TRAIN_CURRENT_BRANCH:-false}
#shellcheck disable=SC2034
readonly GH_MERGE_TRAIN_STACK_SUPPORT=${GH_MERGE_TRAIN_STACK_SUPPORT:-false}

#shellcheck disable=SC1091
source "$BASEDIR/includes/common.sh"
#shellcheck disable=SC1091
source "$BASEDIR/includes/pr-helpers.sh"
#shellcheck disable=SC1091
source "$BASEDIR/includes/file-support.sh"
#shellcheck disable=SC1091
source "$BASEDIR/includes/merge-support.sh"
#shellcheck disable=SC1091
source "$BASEDIR/includes/stack-support.sh"

#shellcheck disable=SC2154
usage() {
  local exit=${1:-1}
  cat <<EOF

Usage: gh merge-train [flags] [pr...]

This is a fake merge train that rebases, approves, and squash-merges each argument

- If no <pr> is supplied the PR for the current branch is used
  (based on 'GH_MERGE_TRAIN_CURRENT_BRANCH')
- Terminates with a warning if the current branch is the default branch.

In effect it takes some toil out of your life because we end up with this:

'gh merge-train 25 26 27' resolves to

for PR in 25 26 27 do
  gh pr update-branch PR --rebase
  while in_progress do
    gh pr checks PR --watch
  done
  if success then
    gh pr review --approve PR
    gh squash-merge PR --use-default-msg
  fi
done

Flags
  -m, --merge merge rather than rebase when updating the pr branch
  -i, --inputfile file containing a newline separated list of PR url/numbers to process

env:
  GH_POLL_INTERVAL_SECS             : interval between re-attempts              : [$POLL_INTERVAL_SECS]
  GH_MERGE_TRAIN_MAX_ATTEMPTS       : how many times to attempt an update       : [$GH_MERGE_TRAIN_MAX_ATTEMPTS]
  GH_MERGE_TRAIN_BOT_LABEL          : optional label to apply to a bot PR.      : [$GH_MERGE_TRAIN_BOT_LABEL]
  GH_MERGE_TRAIN_DEPENDABOT_REBASE  : if 'true' use @dependabot rebase          : [$GH_MERGE_TRAIN_DEPENDABOT_REBASE]
  GH_MERGE_TRAIN_DEPENDABOT_RECREATE: if 'true' use @dependabot recreate        : [$GH_MERGE_TRAIN_DEPENDABOT_RECREATE]
  GH_MERGE_TRAIN_RETRY_FAILED_JOBS  : Because you have flaky jobs for reasons   : [$GH_MERGE_TRAIN_RETRY_FAILED_JOBS]
  GH_MERGE_TRAIN_CURRENT_BRANCH     : merge train the current branch if no args : [$GH_MERGE_TRAIN_CURRENT_BRANCH]
  GH_MERGE_TRAIN_STACK_SUPPORT      : experimental 'gh stack' support           : [$GH_MERGE_TRAIN_STACK_SUPPORT]
EOF
  exit "$exit"
}

__current_branch_pr() {
  local current default pr_number
  current=$(git branch --show-current)
  default=$(gh repo view --json defaultBranchRef --jq ".defaultBranchRef.name")
  if [[ "$current" == "$default" ]]; then
    echo "⚠️ on default branch, cannot determine PR" >&2
    exit 1
  fi
  pr_number=$(gh pr view --json number --jq ".number" 2>/dev/null || true)
  if [[ -z "$pr_number" ]]; then
    echo "⚠️ no PR found for current branch" >&2
    exit 1
  fi
  echo "$pr_number"
}

stack_or_merge() {
  local first="true"
  local stack_num=""
  local stack_or_pr

  for stack_or_pr in "$@"; do
    if [[ "$first" != "true" ]]; then
      wait_quietly "💤..."
    fi
    first="false"
    stack_num=$(gh_stack_get_stack_num "$stack_or_pr")
    if [[ -n "$stack_num" ]]; then
      if [[ "$GH_MERGE_TRAIN_STACK_SUPPORT" == "true" ]]; then
        echo "🔎 stack#$stack_num wraps $stack_or_pr and stack-support enabled"
        stack_merge "$stack_num"
      else
        echo "🔎 $stack_or_pr is part of a stack, stack-support not enabled"
      fi
    else
      merge_train "$stack_or_pr"
    fi
  done
}

{
  inputfile=""
  ARGS=$(getopt --options 'mhi:' --longoptions 'inputfile:,merge,help' -- "${@}")
  eval set -- "$ARGS"
  while true; do
    case "${1}" in
    --merge | -m)
      #shellcheck disable=SC2034
      GH_MERGE_TRAIN_REBASE="false"
      shift
      ;;
    --inputfile | -i)
      inputfile="$2"
      shift 2
      ;;
    -h | --help)
      usage "0"
      ;;
    --)
      shift
      break
      ;;
    *)
      usage
      ;;
    esac
  done
  if [[ "$#" -eq 0 && -z "$inputfile" ]]; then
    if [[ "$GH_MERGE_TRAIN_CURRENT_BRANCH" == "true" ]]; then
      mapfile -t _prs < <(__current_branch_pr)
      set -- "${_prs[@]}"
    else
      usage
    fi
  fi
  if [[ -n "$inputfile" ]]; then
    process_entries_in "$inputfile"
  else
    stack_or_merge "$@"
  fi
}
